---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

# UTF8MB4 has limited support in older MySQL versions.
# Remove this configuration if you experience issues.
---
Name: myproject-database
---
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

# Coba Middleware
# ---
# Name: myrequestprocessors
# After:
#   - requestprocessors
# ---
# SilverStripe\Core\Injector\Injector:
#   SpecialRouteMiddleware:
#     class: SilverStripe\Control\Middleware\RequestHandlerMiddlewareAdapter
#     properties:
#       RequestHandler: HomeController
#       Middlewares:
#         - AuthMiddleware
# SilverStripe\Control\Director:
#   rules:
#     special\section:
#       Controller: SpecialRouteMiddleware